project_id = "zuksvsxnchwskqytuxxq"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.complete-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.update-subscription-quantity]
verify_jwt = false

[functions.send-schedule-notification]
verify_jwt = true
