project_id = "zuksvsxnchwskqytuxxq"

[functions.confirm-schedule]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.complete-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.update-subscription-quantity]
verify_jwt = true

[functions.send-schedule-notification]
verify_jwt = true

[functions.send-schedule-reminders]
verify_jwt = false

[functions.auto-notify-schedule]
verify_jwt = false

[functions.n8n-webhook]
verify_jwt = false

[functions.create-support-checkout]
verify_jwt = true

[functions.generate-smart-schedule]
verify_jwt = true
